### ISSUE TITLE
can you provide predict.py code?

### ISSUE THREAD

**Issue by ai-motive** [Green-Wood/BTTR#3]
Hi ~ @Green-Wood.

I feel grateful mind for your help.
I wanna get `predict.py` code that prints latex from an input image.
If this code is provided, it will be very useful to others as well.

Best regards.

**Comment by Green-Wood** [comment]
Hi there, sorry for the corrupted `test_step` code in the last commit. This time we made two changes:
1. We correct the mistake in `test_step`, now you can run `test.py` to get a zip file of predicted CROHME LaTeX results.
2. We provide `predict.ipynb` notebook in the **example** folder for a tiny demo.

Hope that can help you.

**Comment by ThakurRajAnand** [comment]
@Green-Wood I tried predict.ipynb by passing the pretrained weights you provided but it is giving following error. Am I missing something?

![image](https://user-images.githubusercontent.com/2418110/121954443-60e21480-cd7c-11eb-8d55-73b1d13b0442.png)

**Comment by Green-Wood** [comment]
Sorry, I updated my model structure but forgot to update the given pretrained model. I will upload the newest version of pretrained model later.

**Comment by Green-Wood** [comment]
> @Green-Wood I tried predict.ipynb by passing the pretrained weights you provided but it is giving following error. Am I missing something?
> 
> ![image](https://user-images.githubusercontent.com/2418110/121954443-60e21480-cd7c-11eb-8d55-73b1d13b0442.png)

Sorry, I updated my model structure but forgot to update the given pretrained model. I will upload the newest version of pretrained model later.

**Comment by ThakurRajAnand** [comment]
@Green-Wood  Thanks. It would be helpful if you can share the model soon. Also, I have some private data which is mix of text and equations. Do you think same architecture would work for it. Happy to discuss over call if you are keen to know more.

**Comment by Green-Wood** [comment]
@ThakurRajAnand Because our model deals with the image-to-string problem, I think the same architecture could be used in both text and equation. Feel free to discuss more with me via email.

Another  good model for handling text and equation: [MASTER](https://github.com/jiangxiluning/MASTER-TF)

**Comment by ai-motive** [comment]
@Green-Wood I have question. It's different from the above.
Can you add beam_search() option for batch images. (not multiple image to one result, multiple image to multiple result)

**Comment by Green-Wood** [comment]
@ThakurRajAnand I've published a new pretrained model v2.0 in the release. Please clone the latest repo and re-install the conda environment to get the correct dependencies.

**Comment by Green-Wood** [comment]
> @Green-Wood I have question. It's different from the above.
> Can you add beam_search() option for batch images. (not use datamodule because only to use image feature)

@ai-motive Hi, I did not realize batch optimized version of beam search. Images can only be parsed one at a time. You can contribute your code if you can realize it.

**Comment by thakuranandcolearn** [comment]
@Green-Wood I trained my own model and was able to make predict.ipynb without any issue. 

Are you aware of a good dataset with labels (text + latex) which is combination of Text and Equation to train your architecture?  I looked at ICDAR 2021 data but it seems to be over focused on Tables https://competitions.codalab.org/competitions/26979#learn_the_details

**Comment by Green-Wood** [comment]
> @Green-Wood I trained my own model and was able to make predict.ipynb without any issue.
> 
> Are you aware of a good dataset with labels (text + latex) which is combination of Text and Equation to train your architecture? I looked at ICDAR 2021 data but it seems to be over focused on Tables https://competitions.codalab.org/competitions/26979#learn_the_details

@thakuranandcolearn What type of text and equation do you mean (printed, handwritten, or scene text)?

**Comment by thakuranandcolearn** [comment]
Mostly printed for training as I would be able to apply some semi-supervised learning later using the internal un-labeled data. Below is an example image. 

![image](https://user-images.githubusercontent.com/84895148/122074548-f03c0600-ce16-11eb-8948-265378864331.png)

**Comment by Green-Wood** [comment]
@thakuranandcolearn I think [IM2LATEX-100K](https://www.kaggle.com/shahrukhkhan/im2latex100k) dataset might be a good choice for you. It contains 100K printed formula pictures and the corresponding LaTeX labels.

**Comment by thakuranandcolearn** [comment]
@Green-Wood Yes. I was going through this dataset. Thanks for sharing Kaggle link. Which approach would you recommend might be better?

**Approach 1** 
Train the model on IM2LATEX-100k and predict on patches of bounding box detected in text + equations images. Below is example of what I can detect in different patches in one of the text + equation image 

![image](https://user-images.githubusercontent.com/84895148/122077849-bae4e780-ce19-11eb-9cb1-19661d6d5a52.png)


**Approach 2**
Combine IM2LATEX-100k + internal text only images to train the model and then make prediction on whole image

**Comment by Green-Wood** [comment]
@thakuranandcolearn Sorry I don't know what you mean about internal text, could you explain it in more detail?

**Comment by thakuranandcolearn** [comment]
@Green-Wood I mean collection of images I have where OCR works with high confidence to extract text and probably doesn't have any equations.

**Comment by Green-Wood** [comment]
@thakuranandcolearn I think approach 1 might be better if you can distinguish between text and formula properly.

For some works dealing with formula detection, you may refer to [ICDAR2021 Competition on Mathematical Formula Detection](http://transcriptorium.eu/~htrcontest/MathsICDAR2021/).

Hope that can help you.

**Comment by thakuranandcolearn** [comment]
@Green-Wood Thanks a lot for your patience and reply. I will share the results I get using BTTR in few weeks.

**Comment by chakshu-dhannawat** [comment]
> @Green-Wood I trained my own model and was able to make predict.ipynb without any issue.
> 
> Are you aware of a good dataset with labels (text + latex) which is combination of Text and Equation to train your architecture? I looked at ICDAR 2021 data but it seems to be over focused on Tables https://competitions.codalab.org/competitions/26979#learn_the_details

@thakuranandcolearn , Can you please provide me with an predict.py file for this, I am facing several errors in the beam_search code provided, due to the NaN values being returned by the heads, and also Mask values being non boolean. Thanks in advance!
