### ISSUE TITLE
Val_exprate = 0 

### ISSUE THREAD

**Issue by qingqianshuying** [Green-Wood/BTTR#4]
When I retrained the  model according to the instruction, the val_exprate was always 0.00, did anyone encounter this problem, thank you! (I has not modified any codes)
@Green-Wood

**Comment by Green-Wood** [comment]
Hi. In my own experiment, the `val_exprate` starts increasing after 5 epochs.

Could you provide more details about your experiment configuration? (`conda list`, gpus, etc......)

![image](https://user-images.githubusercontent.com/31267545/119995925-b38fa280-c000-11eb-982f-85fb07df11da.png)

**Comment by qingqianshuying** [comment]
Thank you for your reply ! Here are the experiment details, the running result, the conda list and the gpus, looking forward to your help
![bttr out](https://user-images.githubusercontent.com/26625249/120130402-aa692600-c1f8-11eb-988c-e4a8aa8f8a9f.png)
![conda list3](https://user-images.githubusercontent.com/26625249/120130470-dedce200-c1f8-11eb-8185-f8e2fa08e9ff.png)
![condalist1](https://user-images.githubusercontent.com/26625249/120130475-e0a6a580-c1f8-11eb-8a04-e20f0f7288b9.png)
![condalist2](https://user-images.githubusercontent.com/26625249/120130478-e13f3c00-c1f8-11eb-86ed-34e666b0ed0b.png)
![condalist4](https://user-images.githubusercontent.com/26625249/120130479-e1d7d280-c1f8-11eb-97eb-5432deacda2a.png)
![nvidia25](https://user-images.githubusercontent.com/26625249/120130488-e7cdb380-c1f8-11eb-966c-f7e704bfc52a.png)

**Comment by Green-Wood** [comment]
Hi, I've tested your configuration. 
I noticed that you have `python=3.6.7`  and `pytorch=1.4.0`. 
However, our model requires **`python=3.7` and `pytorch=1.7.0`** in the `README.md` install dependencies instruction. 

You may fix your dependencies' version to fit our requirements, and train it again. **(Don't forget to clone the newest version)**

Hope that can help you.

**Comment by qingqianshuying** [comment]
Thank you very much, I will modify the environment according to the requirements and try the experiment again
