### ISSUE TITLE
how to use TensorBoard?

### ISSUE THREAD

**Issue by win5923** [Green-Wood/BTTR#7]
hello i don't know how to add scalar to TensorBoard? I want to do this kind of topic, hoping to improve some ExpRate, but I don’t know much about lightning TensorBoard.

**Comment by win5923** [comment]
![image](https://user-images.githubusercontent.com/56353753/138238481-0e846cf8-6590-4477-8f75-07bb61a89fb4.png)
Does this need to be added?

**Comment by win5923** [comment]
![image](https://user-images.githubusercontent.com/56353753/142215902-e48dd10d-92bc-4d21-8571-9f0b1d905d43.png)
hello again, i want to ask what are #[b,], # [b, 1, H, W] ,  # [b, H, W] , # [b, l] mean? thx

**Comment by Green-Wood** [comment]
Well, these are just some shape descriptions of these tensors. 
For example:
```
b: batch size
1: we have just one input channel
H: height of input image
W: width of input image
l: length of latex tokens
```

**Comment by win5923** [comment]
![image](https://user-images.githubusercontent.com/56353753/142223738-d362ebc2-68b8-4022-97af-0f4cbba59e58.png)

Excuse me, you already have batch above, why do you still need to define class batch below?

![image](https://user-images.githubusercontent.com/56353753/142223844-2daa5c8d-6787-49c4-a6f1-cce793d1abe8.png)

**Comment by Green-Wood** [comment]
Because different images may have different sizes, you need to collate images in one batch into a single tensor in `Batch` class.

**Comment by win5923** [comment]
Thank you very much, I see.

**Comment by win5923** [comment]
![image](https://user-images.githubusercontent.com/56353753/142262994-d96dcf64-5d6d-4f23-a5d8-771117edf0c2.png)
Sorry for another question,i wonder know what is batch in def collate_fn(batch): .I really confused about this parameter and don't know what collate_fn do what.

**Comment by win5923** [comment]
想请问如果我想把transformer模型换成vit可行吗,因为这好像不是分类问题,我搞了好几天,还是卡在一些前向传递参数的问题,想问问大佬如果想换一个模型该如何修改
